// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_INCLUDED_message_2eproto
#define PROTOBUF_INCLUDED_message_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_message_2eproto 

namespace protobuf_message_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_message_2eproto
namespace PositionInfo {
class Data3d;
class Data3dDefaultTypeInternal;
extern Data3dDefaultTypeInternal _Data3d_default_instance_;
class GeneratedPosition;
class GeneratedPositionDefaultTypeInternal;
extern GeneratedPositionDefaultTypeInternal _GeneratedPosition_default_instance_;
}  // namespace PositionInfo
namespace google {
namespace protobuf {
template<> ::PositionInfo::Data3d* Arena::CreateMaybeMessage<::PositionInfo::Data3d>(Arena*);
template<> ::PositionInfo::GeneratedPosition* Arena::CreateMaybeMessage<::PositionInfo::GeneratedPosition>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace PositionInfo {

// ===================================================================

class Data3d : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PositionInfo.Data3d) */ {
 public:
  Data3d();
  virtual ~Data3d();

  Data3d(const Data3d& from);

  inline Data3d& operator=(const Data3d& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Data3d(Data3d&& from) noexcept
    : Data3d() {
    *this = ::std::move(from);
  }

  inline Data3d& operator=(Data3d&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Data3d& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Data3d* internal_default_instance() {
    return reinterpret_cast<const Data3d*>(
               &_Data3d_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Data3d* other);
  friend void swap(Data3d& a, Data3d& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Data3d* New() const final {
    return CreateMaybeMessage<Data3d>(NULL);
  }

  Data3d* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Data3d>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Data3d& from);
  void MergeFrom(const Data3d& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Data3d* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // required float y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // required float z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:PositionInfo.Data3d)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  float x_;
  float y_;
  float z_;
  friend struct ::protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GeneratedPosition : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PositionInfo.GeneratedPosition) */ {
 public:
  GeneratedPosition();
  virtual ~GeneratedPosition();

  GeneratedPosition(const GeneratedPosition& from);

  inline GeneratedPosition& operator=(const GeneratedPosition& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GeneratedPosition(GeneratedPosition&& from) noexcept
    : GeneratedPosition() {
    *this = ::std::move(from);
  }

  inline GeneratedPosition& operator=(GeneratedPosition&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GeneratedPosition& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GeneratedPosition* internal_default_instance() {
    return reinterpret_cast<const GeneratedPosition*>(
               &_GeneratedPosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(GeneratedPosition* other);
  friend void swap(GeneratedPosition& a, GeneratedPosition& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GeneratedPosition* New() const final {
    return CreateMaybeMessage<GeneratedPosition>(NULL);
  }

  GeneratedPosition* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GeneratedPosition>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GeneratedPosition& from);
  void MergeFrom(const GeneratedPosition& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GeneratedPosition* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .PositionInfo.Data3d position = 3;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 3;
  private:
  const ::PositionInfo::Data3d& _internal_position() const;
  public:
  const ::PositionInfo::Data3d& position() const;
  ::PositionInfo::Data3d* release_position();
  ::PositionInfo::Data3d* mutable_position();
  void set_allocated_position(::PositionInfo::Data3d* position);

  // required uint64 sensorId = 1;
  bool has_sensorid() const;
  void clear_sensorid();
  static const int kSensorIdFieldNumber = 1;
  ::google::protobuf::uint64 sensorid() const;
  void set_sensorid(::google::protobuf::uint64 value);

  // required uint64 timestamp_usec = 2;
  bool has_timestamp_usec() const;
  void clear_timestamp_usec();
  static const int kTimestampUsecFieldNumber = 2;
  ::google::protobuf::uint64 timestamp_usec() const;
  void set_timestamp_usec(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:PositionInfo.GeneratedPosition)
 private:
  void set_has_sensorid();
  void clear_has_sensorid();
  void set_has_timestamp_usec();
  void clear_has_timestamp_usec();
  void set_has_position();
  void clear_has_position();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::PositionInfo::Data3d* position_;
  ::google::protobuf::uint64 sensorid_;
  ::google::protobuf::uint64 timestamp_usec_;
  friend struct ::protobuf_message_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Data3d

// required float x = 1;
inline bool Data3d::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Data3d::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Data3d::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Data3d::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Data3d::x() const {
  // @@protoc_insertion_point(field_get:PositionInfo.Data3d.x)
  return x_;
}
inline void Data3d::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:PositionInfo.Data3d.x)
}

// required float y = 2;
inline bool Data3d::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Data3d::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Data3d::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Data3d::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Data3d::y() const {
  // @@protoc_insertion_point(field_get:PositionInfo.Data3d.y)
  return y_;
}
inline void Data3d::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:PositionInfo.Data3d.y)
}

// required float z = 3;
inline bool Data3d::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Data3d::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Data3d::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Data3d::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float Data3d::z() const {
  // @@protoc_insertion_point(field_get:PositionInfo.Data3d.z)
  return z_;
}
inline void Data3d::set_z(float value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:PositionInfo.Data3d.z)
}

// -------------------------------------------------------------------

// GeneratedPosition

// required uint64 sensorId = 1;
inline bool GeneratedPosition::has_sensorid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GeneratedPosition::set_has_sensorid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GeneratedPosition::clear_has_sensorid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GeneratedPosition::clear_sensorid() {
  sensorid_ = GOOGLE_ULONGLONG(0);
  clear_has_sensorid();
}
inline ::google::protobuf::uint64 GeneratedPosition::sensorid() const {
  // @@protoc_insertion_point(field_get:PositionInfo.GeneratedPosition.sensorId)
  return sensorid_;
}
inline void GeneratedPosition::set_sensorid(::google::protobuf::uint64 value) {
  set_has_sensorid();
  sensorid_ = value;
  // @@protoc_insertion_point(field_set:PositionInfo.GeneratedPosition.sensorId)
}

// required uint64 timestamp_usec = 2;
inline bool GeneratedPosition::has_timestamp_usec() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GeneratedPosition::set_has_timestamp_usec() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GeneratedPosition::clear_has_timestamp_usec() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GeneratedPosition::clear_timestamp_usec() {
  timestamp_usec_ = GOOGLE_ULONGLONG(0);
  clear_has_timestamp_usec();
}
inline ::google::protobuf::uint64 GeneratedPosition::timestamp_usec() const {
  // @@protoc_insertion_point(field_get:PositionInfo.GeneratedPosition.timestamp_usec)
  return timestamp_usec_;
}
inline void GeneratedPosition::set_timestamp_usec(::google::protobuf::uint64 value) {
  set_has_timestamp_usec();
  timestamp_usec_ = value;
  // @@protoc_insertion_point(field_set:PositionInfo.GeneratedPosition.timestamp_usec)
}

// required .PositionInfo.Data3d position = 3;
inline bool GeneratedPosition::has_position() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GeneratedPosition::set_has_position() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GeneratedPosition::clear_has_position() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GeneratedPosition::clear_position() {
  if (position_ != NULL) position_->Clear();
  clear_has_position();
}
inline const ::PositionInfo::Data3d& GeneratedPosition::_internal_position() const {
  return *position_;
}
inline const ::PositionInfo::Data3d& GeneratedPosition::position() const {
  const ::PositionInfo::Data3d* p = position_;
  // @@protoc_insertion_point(field_get:PositionInfo.GeneratedPosition.position)
  return p != NULL ? *p : *reinterpret_cast<const ::PositionInfo::Data3d*>(
      &::PositionInfo::_Data3d_default_instance_);
}
inline ::PositionInfo::Data3d* GeneratedPosition::release_position() {
  // @@protoc_insertion_point(field_release:PositionInfo.GeneratedPosition.position)
  clear_has_position();
  ::PositionInfo::Data3d* temp = position_;
  position_ = NULL;
  return temp;
}
inline ::PositionInfo::Data3d* GeneratedPosition::mutable_position() {
  set_has_position();
  if (position_ == NULL) {
    auto* p = CreateMaybeMessage<::PositionInfo::Data3d>(GetArenaNoVirtual());
    position_ = p;
  }
  // @@protoc_insertion_point(field_mutable:PositionInfo.GeneratedPosition.position)
  return position_;
}
inline void GeneratedPosition::set_allocated_position(::PositionInfo::Data3d* position) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete position_;
  }
  if (position) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      position = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    set_has_position();
  } else {
    clear_has_position();
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:PositionInfo.GeneratedPosition.position)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace PositionInfo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_message_2eproto
